// Typical "base model" per brand, used for the car illustration.
const BASE_MODELS: Record<string, string> = {
  audi: "A6",
  bmw: "E92 3-Series",
  "mercedes-benz": "C200",
  mercedes: "C200",
  volvo: "V70",
  volkswagen: "Golf",
  vw: "Golf",
  toyota: "Corolla",
  ford: "Focus",
  opel: "Astra",
  peugeot: "308",
  renault: "Clio",
  citroën: "C4",
  citroen: "C4",
  skoda: "Octavia",
  "škoda": "Octavia",
  seat: "Leon",
  cupra: "Leon",
  kia: "Ceed",
  hyundai: "i30",
  mazda: "Mazda 3",
  honda: "Civic",
  nissan: "Qashqai",
  subaru: "Impreza",
  mitsubishi: "Outlander",
  suzuki: "Swift",
  saab: "9-3",
  tesla: "Model 3",
  polestar: "Polestar 2",
  porsche: "911",
  jaguar: "XF",
  "land rover": "Discovery",
  lexus: "IS",
  mini: "Cooper",
  fiat: "500",
  alfa: "Giulia",
  "alfa romeo": "Giulia",
  dacia: "Sandero",
  jeep: "Cherokee",
  chevrolet: "Cruze",
  bentley: "Continental",
  maserati: "Ghibli",
  ferrari: "488",
  lamborghini: "Huracán",
  "aston martin": "DB11",
  "rolls-royce": "Ghost",
  mg: "MG4",
  byd: "Atto 3",
  lada: "Niva",
  smart: "Fortwo",
  genesis: "G70",
  infiniti: "Q50",
  "ds": "DS 7",
};

export function baseModelFor(make: string): string {
  return BASE_MODELS[make.trim().toLowerCase()] ?? "";
}
