/** Official web domains per car brand, used for brand logo lookup. */
export const BRAND_DOMAINS: Record<string, string> = {
  Abarth: "abarth.com",
  "Alfa Romeo": "alfaromeo.com",
  Alpine: "alpinecars.com",
  "Aston Martin": "astonmartin.com",
  Audi: "audi.com",
  Bentley: "bentleymotors.com",
  BMW: "bmw.com",
  Bugatti: "bugatti.com",
  Buick: "buick.com",
  BYD: "byd.com",
  Cadillac: "cadillac.com",
  Chevrolet: "chevrolet.com",
  Chrysler: "chrysler.com",
  "Citroën": "citroen.com",
  Cupra: "cupraofficial.com",
  Dacia: "dacia.com",
  Daewoo: "gm.com",
  Daihatsu: "daihatsu.com",
  Dodge: "dodge.com",
  DS: "dsautomobiles.com",
  Ferrari: "ferrari.com",
  Fiat: "fiat.com",
  Fisker: "fiskerinc.com",
  Ford: "ford.com",
  Genesis: "genesis.com",
  GMC: "gmc.com",
  "Great Wall": "gwm.com.cn",
  Honda: "honda.com",
  Hummer: "gmc.com",
  Hyundai: "hyundai.com",
  Infiniti: "infiniti.com",
  Isuzu: "isuzu.co.jp",
  Iveco: "iveco.com",
  Jaguar: "jaguar.com",
  Jeep: "jeep.com",
  Kia: "kia.com",
  Koenigsegg: "koenigsegg.com",
  Lada: "lada.ru",
  Lamborghini: "lamborghini.com",
  Lancia: "lancia.com",
  "Land Rover": "landrover.com",
  Lexus: "lexus.com",
  Lincoln: "lincoln.com",
  Lotus: "lotuscars.com",
  Lucid: "lucidmotors.com",
  Mahindra: "mahindra.com",
  Maserati: "maserati.com",
  Maybach: "mercedes-benz.com",
  Mazda: "mazda.com",
  McLaren: "mclaren.com",
  "Mercedes-Benz": "mercedes-benz.com",
  MG: "mg.co.uk",
  Mini: "mini.com",
  Mitsubishi: "mitsubishi-motors.com",
  Morgan: "morgan-motor.com",
  Nio: "nio.com",
  Nissan: "nissan-global.com",
  Opel: "opel.com",
  Pagani: "pagani.com",
  Peugeot: "peugeot.com",
  Polestar: "polestar.com",
  Pontiac: "gm.com",
  Porsche: "porsche.com",
  Proton: "proton.com",
  Renault: "renault.com",
  Rimac: "rimac-automobili.com",
  Rivian: "rivian.com",
  "Rolls-Royce": "rolls-roycemotorcars.com",
  Rover: "landrover.com",
  Saab: "saab.com",
  Seat: "seat.com",
  "Škoda": "skoda-auto.com",
  Smart: "smart.com",
  SsangYong: "kg-mobility.com",
  Subaru: "subaru.com",
  Suzuki: "globalsuzuki.com",
  Tesla: "tesla.com",
  Toyota: "toyota.com",
  Vauxhall: "vauxhall.co.uk",
  Volkswagen: "vw.com",
  Volvo: "volvocars.com",
  Xpeng: "xpeng.com",
  Zeekr: "zeekrlife.com",
};

export function brandDomain(make: string): string | null {
  const key = make.trim().toLowerCase();
  const match = Object.keys(BRAND_DOMAINS).find((b) => b.toLowerCase() === key);
  return match ? (BRAND_DOMAINS[match] ?? null) : null;
}
