/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiagnosRouteImport } from './routes/diagnos'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SnabbkollRouteImport } from './routes/snabbkoll'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosRoute = DiagnosRouteImport.update({
  id: '/diagnos',
  path: '/diagnos',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SnabbkollRoute = SnabbkollRouteImport.update({
  id: '/snabbkoll',
  path: '/snabbkoll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnos': typeof DiagnosRoute
  '/garage': typeof GarageRoute
  '/history': typeof HistoryRoute
  '/profil': typeof ProfilRoute
  '/snabbkoll': typeof SnabbkollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnos': typeof DiagnosRoute
  '/garage': typeof GarageRoute
  '/history': typeof HistoryRoute
  '/profil': typeof ProfilRoute
  '/snabbkoll': typeof SnabbkollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnos': typeof DiagnosRoute
  '/garage': typeof GarageRoute
  '/history': typeof HistoryRoute
  '/profil': typeof ProfilRoute
  '/snabbkoll': typeof SnabbkollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diagnos'
    | '/garage'
    | '/history'
    | '/profil'
    | '/snabbkoll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/diagnos'
    | '/garage'
    | '/history'
    | '/profil'
    | '/snabbkoll'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/diagnos'
    | '/garage'
    | '/history'
    | '/profil'
    | '/snabbkoll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DiagnosRoute: typeof DiagnosRoute
  GarageRoute: typeof GarageRoute
  HistoryRoute: typeof HistoryRoute
  ProfilRoute: typeof ProfilRoute
  SnabbkollRoute: typeof SnabbkollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnos': {
      id: '/diagnos'
      path: '/diagnos'
      fullPath: '/diagnos'
      preLoaderRoute: typeof DiagnosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snabbkoll': {
      id: '/snabbkoll'
      path: '/snabbkoll'
      fullPath: '/snabbkoll'
      preLoaderRoute: typeof SnabbkollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DiagnosRoute: DiagnosRoute,
  GarageRoute: GarageRoute,
  HistoryRoute: HistoryRoute,
  ProfilRoute: ProfilRoute,
  SnabbkollRoute: SnabbkollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
